# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gibbs_cpp <- function(A, X, V, nn, initial_beta, initial_alpha, initial_inv_sigma2_beta, initial_inv_sigma2_alpha, initial_inv_a_beta, initial_inv_tau2, initial_inv_a_tau, a_alpha = 0.1, b_alpha = 0.1, nu_0 = 1, eta2_0 = 1, nu_1 = 1, eta2_1 = 1, horseshoe = TRUE, mcmc_sample = 500L, burnin = 5000L, thinning = 10L, paras_diff_tol = 1e-6, verbose = 5000L, save_profile = 1L) {
    .Call(`_SeaBASS_Gibbs_cpp`, A, X, V, nn, initial_beta, initial_alpha, initial_inv_sigma2_beta, initial_inv_sigma2_alpha, initial_inv_a_beta, initial_inv_tau2, initial_inv_a_tau, a_alpha, b_alpha, nu_0, eta2_0, nu_1, eta2_1, horseshoe, mcmc_sample, burnin, thinning, paras_diff_tol, verbose, save_profile)
}

SeaBASS_cpp <- function(A, X, V, nn, initial_beta, initial_alpha, initial_inv_sigma2_beta, initial_inv_sigma2_alpha, initial_inv_a_beta, initial_inv_tau2, initial_inv_a_tau, mu_beta, mu_alpha, horseshoe = FALSE, a_alpha = 0.1, b_alpha = 0.1, nu_0 = 1, eta2_0 = 1, nu_1 = 1, eta2_1 = 1, max_iter = 1000L, paras_diff_tol = 1e-6, ELBO_stop = 1L, ELBO_diff_tol = 1e-6, verbose = 0L, save_profile = 1L) {
    .Call(`_SeaBASS_SeaBASS_cpp`, A, X, V, nn, initial_beta, initial_alpha, initial_inv_sigma2_beta, initial_inv_sigma2_alpha, initial_inv_a_beta, initial_inv_tau2, initial_inv_a_tau, mu_beta, mu_alpha, horseshoe, a_alpha, b_alpha, nu_0, eta2_0, nu_1, eta2_1, max_iter, paras_diff_tol, ELBO_stop, ELBO_diff_tol, verbose, save_profile)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_SeaBASS_rcpp_pgdraw`, b, c)
}

rcpparma_hello_world <- function() {
    .Call(`_SeaBASS_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_SeaBASS_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_SeaBASS_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_SeaBASS_rcpparma_bothproducts`, x)
}

